### ISSUE TITLE
Подготовить для npm

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#14]
Подготовить для npm, чтобы можно было вставлять в разные проекты (см. [как тут](https://www.freecodecamp.org/news/how-to-make-a-beautiful-tiny-npm-package-and-publish-it-2881d4307f78/)). `bootstrap-vue/nuxt` должно остаться в dependencies

**Comment by DwarGrak** [comment]
Добавил индекс с экспортом
