### ISSUE TITLE
Надо сделать колл-беки

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#15]
Надо сделать колл-беки для:
  - Записи данных яйчейки (чтобы каждое изменение таблицы на "горячую" сохранялось в БД)
  - Изменение свойств, добавление или удаление строк и столбцов

Нужен метод (вызваемый в среде, где разворачивается таблица) для того, чтобы записать в таблицу данные.

И описать как работать с колл-беками в `API.md`.

Если не настроены колл-беки, сделать дефолтные, которые просто обращаются к БД (Vuex + localstorage).

**Comment by DwarGrak** [comment]
Для чтения данных с сервера точно нужны колбеки? Сейчас данные получаем, вставляем в таблицу. Т.е. таблица напрямую с сервером не общается. 
Уже есть такие колбеки:
@change - обновление ячейки
@change-aggregating - обновление агрегации по столбцу
@add-row - добавление строки
@del-row - удаление строки
@add-col - добавление столбца
@del-col - удаление столбца
@resize-col - изменение ширины столбца
@move-col - перемещение столбца
Какие то ещё нужны?

**Comment by jumpingrabbit** [comment]
> Для чтения данных с сервера точно нужны колбеки?

Верно, не колбек, а нужен метод (вызваемый в среде, где разворачивается таблица) для того, чтобы записать в таблицу данные.


> Уже есть такие колбеки:
> @change - обновление ячейки
> @change-aggregating - обновление агрегации по столбцу
> @add-row - добавление строки
> @del-row - удаление строки
> @add-col - добавление столбца
> @Del-Col - удаление столбца
> @resize-col - изменение ширины столбца
> @move-col - перемещение столбца
> Какие то ещё нужны?

Вроде хватит, а можно опиcать, как с ними работать в README?

**Comment by DwarGrak** [comment]
Доки сделал. Метод для записи данных не нужен, данные передаются пропсами. Пропсы тоже в доках

**Comment by jumpingrabbit** [comment]
А где Доки ?
