### ISSUE TITLE
Переименовать `Json` to `JSON` при добавления колонки

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#17]
![image](https://user-images.githubusercontent.com/13073856/108793856-a6fe4700-75d8-11eb-841f-b0359fab2ed6.png)

**Comment by DwarGrak** [comment]
У нас нет модального окна добавления колонки. Вместо него выпадающий список 
![image](https://user-images.githubusercontent.com/47111574/112604656-743dad80-8e27-11eb-8ab3-0ef09cb7bc97.png)
Требуется уточнение!

**Comment by jumpingrabbit** [comment]
>Вместо него выпадающий список

OK. Значит там.

**Comment by DwarGrak** [comment]
Готово на dev
