### ISSUE TITLE
При валидации надо указать пользователю, какой тип данных ожидает яйчейка

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#21]
Потому что сейчас не видно:

![image](https://user-images.githubusercontent.com/13073856/108794382-c34eb380-75d9-11eb-8492-47471f6e642f.png)

**Comment by DwarGrak** [comment]
Как это сделать? Можно писать в тултип у иконки или ячейки. Можно ещё что-нибудь придумать. Ошибка может быть не только в типе данных, но и в уникальности значений, а в процентах нельзя было отрицательные ставить вроде. Как тут быть? Нужен видимо текст для каждой ошибки. Или только про типы данных предупреждаем?

**Comment by jumpingrabbit** [comment]
> только про типы данных предупреждаем

Да, наверно пока так.

>  в процентах нельзя было отрицательные ставить вроде

Давай сделаем, чтобы можно было, и значения выше 100%

> но и в уникальности значений

А на это валидации не должно быть

> Как это сделать? Можно писать в тултип у иконки или ячейки.

Да, тултип у ячейки. Давай писать `Expected data format: {название ожидаемого типа данных}`

**Comment by DwarGrak** [comment]
Готово в dev

**Comment by jumpingrabbit** [comment]
Есть баги:

- [ ] После того, как неправильно вводишь значения в тип image, больше не получается ничего вводить
- [ ] после того, как не до конца вёл дату, тоже больше не получается ничего вводить в другие яйчейки

**Comment by DwarGrak** [comment]
Сделал отображение ошибки для ячейки с датой
Сделал пустое значение валидным для ячеек с датой и картинкой

По прежнему работает принцип, что если данные в ячейке не валидные, ячейка остается редактируемой пока данные валидными не станут. В случае ячеек с датой и картинкой при ввода неправильных данных достаточно очистить ячейку, ячейка станет валидной и можно будет снять редактирование.
