### ISSUE TITLE
Переименование колонок

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#23]
Сделать возможность переименовать колонки. См. подчёркивание, как сделано в нашем проекте:

![image](https://user-images.githubusercontent.com/13073856/108800172-8341fd80-75e6-11eb-94af-e0fb951fd7ed.png)

**Comment by DwarGrak** [comment]
Готово в dev

**Comment by jumpingrabbit** [comment]
Можно пожалуйста, чтобы стиль был как у нас в проекте (в том числе и размер шрифта).

Также надо убрать переносимость строк в названии.

**Comment by DwarGrak** [comment]
На иллюстрации-вложении сразу два редактируемых по нажатию поля. Предполагаю, что стили нужно перенести из нижнего поля. Жирность текста и фон ячейки также будут приведены в соответствие с основным сайтом. Перенос текста заменяю на многоточие
