### ISSUE TITLE
Сделать возможность задать высоту таблицы

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#26]
Для программиста, который использует компонент, сделать возможность задать высоту таблицы (в пикселях или в чём-то ещё).

Это нужно, чтобы полоска прокрутки всегда была видна внизу пользователю.

**Comment by jumpingrabbit** [comment]
> Как должна задаваться высота таблицы? Пользователем в интерфейсе или в коде.

В коде, в свойствах таблицы, чтобы программист, который использует компонент, смог её задать.

**Comment by DwarGrak** [comment]
Готово на dev
