### ISSUE TITLE
JSON view

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#35]
Надо сделать возможность посмотреть JSON всей таблицы. То есть нужна кнопка-переключатель, при нажатии на которую весь компонент переходит в режим в просмотра JSON (с помощью того же компонента, который используется при редактировании яйчеек JSON в самой таблице).

При переходе обратно в обычное состояние надо делать валидацию этого JSON.

**Comment by DwarGrak** [comment]
Готово на dev

**Comment by jumpingrabbit** [comment]
Спасибо. Можно пожалуйста сделать кнопку:

* классом `.btn-sm` в бутстрапе справа.
* при нажатии на кнопку, надо поменять её текст на `Return to table view`

**Comment by DwarGrak** [comment]
Сделал кнопку бутстраповской, остальное поменял, добавил отступ снизу
