### ISSUE TITLE
JSON preview

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/vue-bootstrap-advanced-table#6]
Надо сделать так, чтобы JSON показывался не весь, а только первые 100 символов. Потом надо поставить троеточие.

**Comment by shockedbear-conjointly** [comment]
> Надо сделать так, чтобы JSON показывался не весь, а только первые 100 символов. Потом надо поставить троеточие.

@jumpingrabbit лучше ограничить блок с json по высоте, и добавить класс `text-overflow: ellipsis`, тогда он автоматом будет с троеточиями, обрезать до 100 символов и выставление ... не всегда сработает, потому что может быть 100 раз \n, и тогда не будет видно в таком случае

**Comment by DwarGrak** [comment]
text-overflow: ellipsis не учитывает количество знаков, а только ширину поля. Уже сделал, как предлагалось изначально - обрезаю по числу символов. Переделываем?

**Comment by jumpingrabbit** [comment]
> text-overflow: ellipsis

хорошая идея.

>  Уже сделал, как предлагалось изначально - обрезаю по числу символов. Переделываем?

Нет, не переделываем. 

Это будет не такой востребованный тип колонок, поэтому не много пока времени тратим на него.

**Comment by DwarGrak** [comment]
Тогда всё готово
